default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: DEVELOPMENT_DATABASE
  username: postgres

test:
  <<: *default
  encoding: unicode
  database: TEST_DATABASE
  username: postgres

production:
  <<: *default
